name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.2+1
  cloud_firestore: ^0.12.11
  firebase_auth: ^0.15.1
  modal_progress_hud: ^0.1.3
  image_picker: ^0.6.2+1
  firebase_storage: ^3.0.8



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
  fonts:
  - family: fonts1
    fonts:
    - asset: fonts/Girassol-Regular.ttf
